server:
  port: 8080 # gateway-service는 8080 포트 사용 (기본 포트이므로 생략 가능하나 명시)

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: serviceA_route
          uri: http://localhost:8081 # service-a의 주소
          predicates:
            - Path=/serviceA/** # /serviceA/로 시작하는 모든 요청 매칭
          filters: # 이 부분을 추가/수정합니다!
            - StripPrefix=1 # 경로에서 첫 번째 세그먼트(/serviceA)를 제거합니다.
        - id: serviceB_route
          uri: http://localhost:8082 # service-b의 주소
          predicates:
            - Path=/serviceB/** # /serviceB/로 시작하는 모든 요청 매칭
          filters: # 이 부분을 추가/수정합니다!
            - StripPrefix=1 # 경로에서 첫 번째 세그먼트(/serviceB)를 제거합니다.

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG
